repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.8.0
  hooks:
  - id: seed-isort-config
    types: [python]
    exclude: ^migrations/
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    types: [python]
    exclude: ^migrations/
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    types: [python]
    exclude: ^migrations/
